# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_cash_register', '0002_auto_20160810_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('AB', 'Alfa Click'), ('AC', 'Credit/Debit card'), ('GP', 'Cash via terminal'), ('MA', 'MasterPass'), ('MC', 'Mobile phone account'), ('PB', 'Promsvyazbank online-bank'), ('PC', 'Yandex.Money wallet'), ('SB', 'Sberbank Online'), ('WM', 'WebMoney wallet'), ('QS', 'QiWi wallet')], default='PC', editable=False, max_length=2, verbose_name='Payment method'),
        ),
    ]
